### ISSUE TITLE
Exercise61,(c), Chapter3

### ISSUE THREAD

**Issue by TY-Cheng** [alanarnholt/PASWR2E-Book#3]
R code here is
SkewY <- integrate(f = function(x){(x-EY)^3*fx(x)}, lower = 0, upper = Inf)$value / (VY^(3/2))

actually using probability density function of X, fx(x), so the x-EY should be function of X, that is, 0.03X+0.5-EY=0.03X-1.5, thus make the definition domain usable.

Thanks.

**Comment by alanarnholt** [comment]
Thanks for your comment ....but I do not understand your point.  If you do
find errata, please let us know about it on the books errata page
https://github.com/alanarnholt/PASWR2E-Book/issues   You are on the PASWR2
package page.  If you find bugs in the software this is where you should
post a note so we can fix them.

Alan T. Arnholt
Professor
Department of Mathematical Sciences
Appalachian State University
T:(828)262-2863
F:(828)265-8617
http://www1.appstate.edu/~arnholta/

**Comment by alanarnholt** [comment]
Thanks for your comment ....but I do not understand your point.  If you do find errata, please let us know about it on the books errata page https://github.com/alanarnholt/PASWR2E-Book/issues .  You are on the PASWR2 package page.  If you find bugs in the software, this is where you should post a note so we can fix them.
